baseURL = "https://ledanh.cf/"
languageCode = "en-us"
title = "Lê Danh"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    description = "Một kỹ sư phần mềm ham học hỏi, thích chạy bộ và sống nội tâm"
    githubUsername = "#"
    accent = "red"
    showBorder = false
    backgroundColor = "white"
    font = "Arial" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    favicon = "img/favicon.ico"
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
    tag = "tags"
    category = "categories"

[[menu.main]]
    url = "/"
    name = "\"Nhà\""
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "Về Mình"
    weight = 2

[[menu.main]]
    url = "/tech_post/"
    name = "Kỹ Thuật"
    weight = 3

[[menu.main]]
    url = "/though/"
    name = "Quan Điểm - Suy Nghĩ"
    weight = 4

[[menu.main]]
    url = "/list/"
    name = "\"Danh Sách Xô\""
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:lcdanh110628@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/lcongdanh/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://facebook.com/danh.lecong/"
    name = "fab fa-facebook"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/lcongdanh/"
    name = "fab fa-linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/users/13967065/danh-le/"
    name = "fab fa-stack-overflow"
    weight = 5
